server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: snowflake
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
zhong:
  redis:
    lock:
      enable: true
      keep-alive:
      factor:
